#!/bin/bash

source "$(dirname "$0")/logging.sh"

# Export all environment variables to .env file
export_environment_variables() {
    local output_file=${1:-.env}
    
    log_info "Exporting environment variables to $output_file"
    
    cat <<EOF > "$output_file"
DOMAIN="$DOMAIN"
ENABLE_HTTPS="$ENABLE_HTTPS"
USERNAME="$USERNAME"
PASSWORD="$PASSWORD"
MODULES="$MODULES"
GITEA_HOSTNAME="$GITEA_HOSTNAME"
MYSQL_ROOT_PASSWORD="$MYSQL_ROOT_PASSWORD"
ENTRYPOINT="$ENTRYPOINT"
GITEA_PROTOCOL="$GITEA_PROTOCOL"
REGISTRY_PORT="$REGISTRY_PORT"
REGISTRATION_TOKEN="$REGISTRATION_TOKEN"
BASE_DIR="$BASE_DIR"
CONFIG_DIR="$CONFIG_DIR"
SCRIPTS_DIR="$SCRIPTS_DIR"
DOCKER_DIR="$DOCKER_DIR"
DATA_DIR="$DATA_DIR"
DYNAMIC_DOCKER_DIR="$DYNAMIC_DOCKER_DIR"
DYNAMIC_FRAMEWORKS_DIR="$DYNAMIC_FRAMEWORKS_DIR"
EOF
}
